Repository MIT-Emerging-Talent/ET6-foundations-group-13, pull requests merged in 2024-12, with the labels that each got.

#8 Add test file detection to CI and improve setup documentation
  .github/ISSUE_TEMPLATE/help_wanted.md
  .github/ISSUE_TEMPLATE/meeting_agenda.md
  .github/ISSUE_TEMPLATE/new_challenge.md
  .github/ISSUE_TEMPLATE/question.md
  .github/workflows/ci-checks.yml
  collaboration/guide/0_repository_setup.md
Labels: documentation, enhancement

#10 Updated Group Norms
  collaboration/README.md
  collaboration/group_norms.md
Labels: documentation

#14 Fix Group Norms file
  collaboration/group_norms.md
Labels: fix

#15 Update our repo with Latest Changes from Main Repository
  .github/workflows/ci-checks.yml
  .vscode/settings.json
  solutions/__init__.py
  solutions/tests/__init__.py
Labels: enhancement, fix

#24 Updated Pull Request Template.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#25 Leap year checker
  .vscode/settings.json
  solutions/leap_year_checker.py
  solutions/tests/test_leap_year_checker.py
Labels: challenge
